services: 
  db:
    image: mysql:latest
    volumes: 
      - db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: y6QDxkWA9zH
      MYSQL_DATABASE: cda_hotel_nice
      MYSQL_USER: hotel_nice
      MYSQL_PASSWORD: gbQV97CDpnN
    restart: always
  adminer:
    image: adminer:latest
    depends_on:
     - db
    ports: 
      - "8080:8080"
    restart: always
  php:
    image: webdevops/php-apache-dev
    depends_on:
     - db
    ports: 
      - "80:80"
    volumes:
      - ./app:/app
    restart: always
volumes: 
  db_data: {}